import {
  AmbientSoundId,
  AppDataState,
  Habit,
  HabitCompletionMap,
  RoomObjectId,
  RoomObjectPlacement,
  SceneId,
  SpacePreset,
  TimeOfDay,
  UserPlaylist,
  WeatherType,
} from '../types/app';

export interface SceneMetadata {
  id: SceneId;
  name: string;
  subtitle: string;
  category: 'Indoor' | 'Nature' | 'Transit' | 'Urban' | 'Sci-Fi';
  imageUrl?: string;
  defaultWeather: WeatherType;
  defaultTime: TimeOfDay;
  defaultAmbient: AmbientSoundId;
  skyGradient: [string, string, string];
  accentGlow: string;
  particleType: 'rain' | 'fireflies' | 'dust' | 'snow' | 'stars' | 'sakura' | 'sparks';
}

export const PIXEL_SCENES: SceneMetadata[] = [
  {
    id: 'living_sanctuary',
    name: 'Floating Sanctuary',
    subtitle: 'Sky Terrace & Bioluminescent River',
    category: 'Nature',
    imageUrl: '/src/assets/images/pixel_living_world_sanctuary_1791517842487.jpg',
    defaultWeather: 'clear',
    defaultTime: 'night',
    defaultAmbient: 'nature_night',
    skyGradient: ['#060d1f', '#0f172a', '#1e1b4b'],
    accentGlow: '#2dd4bf',
    particleType: 'fireflies',
  },
  {
    id: 'floating_garden',
    name: 'Spirit Blossom Island',
    subtitle: 'Luminescent Cherry Tree & Waterfall',
    category: 'Nature',
    imageUrl: '/src/assets/images/pixel_floating_garden_shrine_1791517855793.jpg',
    defaultWeather: 'clear',
    defaultTime: 'evening',
    defaultAmbient: 'forest',
    skyGradient: ['#0f172a', '#1e1b4b', '#311042'],
    accentGlow: '#f472b6',
    particleType: 'sakura',
  },
  {
    id: 'astral_observatory',
    name: 'Astral Observatory',
    subtitle: 'Starlit Archive & Golden Astrolabe',
    category: 'Indoor',
    imageUrl: '/src/assets/images/pixel_astral_observatory_library_1791517866426.jpg',
    defaultWeather: 'clear',
    defaultTime: 'night',
    defaultAmbient: 'fireplace',
    skyGradient: ['#090d16', '#172554', '#1e1b4b'],
    accentGlow: '#f59e0b',
    particleType: 'stars',
  },
  {
    id: 'study_room',
    name: 'Study Room',
    subtitle: 'Rainy Night Study Desk',
    category: 'Indoor',
    imageUrl: '/src/assets/images/pixel_scene_study_room_1791479840520.jpg',
    defaultWeather: 'rain',
    defaultTime: 'night',
    defaultAmbient: 'rain',
    skyGradient: ['#0f172a', '#1e1b4b', '#312e81'],
    accentGlow: '#f59e0b',
    particleType: 'rain',
  },
  {
    id: 'rainy_cafe',
    name: 'Rainy Café',
    subtitle: 'Warm Corner Espresso Bar',
    category: 'Indoor',
    imageUrl: '/src/assets/images/pixel_scene_rainy_cafe_1791479855250.jpg',
    defaultWeather: 'rain',
    defaultTime: 'evening',
    defaultAmbient: 'cafe',
    skyGradient: ['#1c1917', '#292524', '#44403c'],
    accentGlow: '#fb923c',
    particleType: 'rain',
  },
  {
    id: 'train_journey',
    name: 'Train Journey',
    subtitle: 'Twilight Mountain Express',
    category: 'Transit',
    imageUrl: '/src/assets/images/pixel_scene_train_journey_1791479867463.jpg',
    defaultWeather: 'clear',
    defaultTime: 'evening',
    defaultAmbient: 'train',
    skyGradient: ['#1e1b4b', '#4c1d95', '#c2410c'],
    accentGlow: '#f97316',
    particleType: 'stars',
  },
  {
    id: 'forest_cabin',
    name: 'Forest',
    subtitle: 'Emerald Woodland Sanctuary',
    category: 'Nature',
    imageUrl: '/src/assets/images/pixel_scene_forest_cabin_1791479879622.jpg',
    defaultWeather: 'clear',
    defaultTime: 'evening',
    defaultAmbient: 'forest',
    skyGradient: ['#064e3b', '#065f46', '#0f172a'],
    accentGlow: '#34d399',
    particleType: 'fireflies',
  },
  {
    id: 'night_library',
    name: 'Library',
    subtitle: 'Grand Vintage Archive',
    category: 'Indoor',
    imageUrl: '/src/assets/images/pixel_scene_night_library_1791479893215.jpg',
    defaultWeather: 'clear',
    defaultTime: 'night',
    defaultAmbient: 'fireplace',
    skyGradient: ['#1e1b4b', '#172554', '#0f172a'],
    accentGlow: '#22c55e',
    particleType: 'dust',
  },
  {
    id: 'night_city',
    name: 'Night City',
    subtitle: 'Neon Skyline Rooftop',
    category: 'Urban',
    imageUrl: '/src/assets/images/pixel_scene_study_room_1791479840520.jpg',
    defaultWeather: 'heavy_rain',
    defaultTime: 'night',
    defaultAmbient: 'rain',
    skyGradient: ['#090d16', '#1e1b4b', '#3b0764'],
    accentGlow: '#818cf8',
    particleType: 'rain',
  },
  {
    id: 'cozy_bedroom',
    name: 'Cozy Bedroom',
    subtitle: 'Warm Lo-Fi Loft Hideaway',
    category: 'Indoor',
    imageUrl: '/src/assets/images/pixel_scene_study_room_1791479840520.jpg',
    defaultWeather: 'rain',
    defaultTime: 'night',
    defaultAmbient: 'rain',
    skyGradient: ['#1e1b4b', '#311042', '#0f172a'],
    accentGlow: '#f472b6',
    particleType: 'dust',
  },
  {
    id: 'train_station',
    name: 'Train Station',
    subtitle: 'Misty Platform at Dusk',
    category: 'Transit',
    imageUrl: '/src/assets/images/pixel_scene_train_journey_1791479867463.jpg',
    defaultWeather: 'rain',
    defaultTime: 'evening',
    defaultAmbient: 'train',
    skyGradient: ['#0f172a', '#1e293b', '#334155'],
    accentGlow: '#38bdf8',
    particleType: 'rain',
  },
  {
    id: 'mountain_cabin',
    name: 'Mountain Cabin',
    subtitle: 'Snowy Alpine Hearth',
    category: 'Nature',
    imageUrl: '/src/assets/images/pixel_scene_forest_cabin_1791479879622.jpg',
    defaultWeather: 'snow',
    defaultTime: 'night',
    defaultAmbient: 'fireplace',
    skyGradient: ['#0f172a', '#1e293b', '#334155'],
    accentGlow: '#fb923c',
    particleType: 'snow',
  },
  {
    id: 'rainy_window',
    name: 'Rainy Window',
    subtitle: 'Bokeh Glass & Storm Drops',
    category: 'Indoor',
    imageUrl: '/src/assets/images/pixel_scene_rainy_cafe_1791479855250.jpg',
    defaultWeather: 'heavy_rain',
    defaultTime: 'night',
    defaultAmbient: 'rain',
    skyGradient: ['#0f172a', '#1e293b', '#090d16'],
    accentGlow: '#60a5fa',
    particleType: 'rain',
  },
  {
    id: 'beach',
    name: 'Beach',
    subtitle: 'Twilight Ocean Breeze',
    category: 'Nature',
    defaultWeather: 'clear',
    defaultTime: 'evening',
    defaultAmbient: 'ocean',
    skyGradient: ['#1e1b4b', '#7c2d12', '#f97316'],
    accentGlow: '#fb923c',
    particleType: 'stars',
  },
  {
    id: 'garden',
    name: 'Garden',
    subtitle: 'Zen Koi & Bamboo Courtyard',
    category: 'Nature',
    imageUrl: '/src/assets/images/pixel_floating_garden_shrine_1791517855793.jpg',
    defaultWeather: 'rain',
    defaultTime: 'afternoon',
    defaultAmbient: 'nature_night',
    skyGradient: ['#064e3b', '#115e59', '#134e4a'],
    accentGlow: '#2dd4bf',
    particleType: 'sakura',
  },
  {
    id: 'space_station',
    name: 'Space Station',
    subtitle: 'Low-Orbit Observation Deck',
    category: 'Sci-Fi',
    defaultWeather: 'clear',
    defaultTime: 'night',
    defaultAmbient: 'brown_noise',
    skyGradient: ['#020617', '#0f172a', '#1e1b4b'],
    accentGlow: '#38bdf8',
    particleType: 'stars',
  },
  {
    id: 'cyberpunk_room',
    name: 'Cyberpunk Room',
    subtitle: 'High-Rise Synth Terminal',
    category: 'Sci-Fi',
    imageUrl: '/src/assets/images/pixel_scene_study_room_1791479840520.jpg',
    defaultWeather: 'storm',
    defaultTime: 'night',
    defaultAmbient: 'rain',
    skyGradient: ['#090d16', '#2e1065', '#4c1d95'],
    accentGlow: '#c084fc',
    particleType: 'rain',
  },
  {
    id: 'japanese_study',
    name: 'Japanese Study',
    subtitle: 'Tatami & Shoji Lantern Room',
    category: 'Indoor',
    imageUrl: '/src/assets/images/pixel_scene_night_library_1791479893215.jpg',
    defaultWeather: 'clear',
    defaultTime: 'evening',
    defaultAmbient: 'nature_night',
    skyGradient: ['#1c1917', '#292524', '#431407'],
    accentGlow: '#f59e0b',
    particleType: 'sakura',
  },
];

export interface MusicTrackMetadata {
  id: string;
  title: string;
  subtitle: string;
  artist?: string;
  description?: string;
  genre: string;
  category: 'ambient' | 'focus' | 'nature' | 'rain' | 'instrumental';
  coverSceneId: SceneId;
  src?: string;
  source?: 'bundled_file' | 'procedural_synth';
  license?: string;
  durationSeconds?: number;
}

export const BUILTIN_MUSIC_TRACKS: MusicTrackMetadata[] = [
  {
    id: 'bundled_velvet_rain_lofi',
    title: 'Velvet Rain Lo-Fi',
    artist: 'Habitra Studio',
    description: 'Warm electric piano chords over gentle rainy window reflections',
    subtitle: 'Bundled CC0 WAV · public/music/rain/',
    genre: 'Rain Lo-Fi',
    category: 'rain',
    coverSceneId: 'rainy_cafe',
    src: './music/rain/velvet-rain-lofi.wav',
    source: 'bundled_file',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 12,
  },
  {
    id: 'bundled_midnight_study_chords',
    title: 'Midnight Study Chords',
    artist: 'Habitra Studio',
    description: 'Deep concentration chord progression for late-night reading',
    subtitle: 'Bundled CC0 WAV · public/music/focus/',
    genre: 'Focus Study',
    category: 'focus',
    coverSceneId: 'study_room',
    src: './music/focus/midnight-study-chords.wav',
    source: 'bundled_file',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 12,
  },
  {
    id: 'bundled_deep_work_pulse',
    title: 'Deep Work Harmonic Pulse',
    artist: 'Habitra Studio',
    description: 'Rhythmic 2Hz harmonic focus bed for coding and study sessions',
    subtitle: 'Bundled CC0 WAV · public/music/focus/',
    genre: 'Deep Focus',
    category: 'focus',
    coverSceneId: 'cyberpunk_room',
    src: './music/focus/deep-work-pulse.wav',
    source: 'bundled_file',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 16,
  },
  {
    id: 'bundled_cozy_hearth_drone',
    title: 'Cozy Hearth Drone',
    artist: 'Habitra Studio',
    description: 'Warm fireside harmonic drone for quiet evening relaxation',
    subtitle: 'Bundled CC0 WAV · public/music/ambient/',
    genre: 'Warm Ambient',
    category: 'ambient',
    coverSceneId: 'cozy_bedroom',
    src: './music/ambient/cozy-hearth-drone.wav',
    source: 'bundled_file',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 12,
  },
  {
    id: 'bundled_starlight_drift_pad',
    title: 'Starlight Drift Pad',
    artist: 'Habitra Studio',
    description: 'Slowly evolving celestial pad for calm evening reflection',
    subtitle: 'Bundled CC0 WAV · public/music/ambient/',
    genre: 'Celestial Ambient',
    category: 'ambient',
    coverSceneId: 'space_station',
    src: './music/ambient/starlight-drift-pad.wav',
    source: 'bundled_file',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 16,
  },
  {
    id: 'bundled_forest_breeze_harmonic',
    title: 'Forest Breeze Harmonic',
    artist: 'Habitra Studio',
    description: 'Organic woodland overtones and serene morning resonance',
    subtitle: 'Bundled CC0 WAV · public/music/nature/',
    genre: 'Nature Harmonic',
    category: 'nature',
    coverSceneId: 'forest_cabin',
    src: './music/nature/forest-breeze-harmonic.wav',
    source: 'bundled_file',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 12,
  },
  {
    id: 'bundled_lantern_acoustic_arp',
    title: 'Lantern Acoustic Arpeggio',
    artist: 'Habitra Studio',
    description: 'Plucked acoustic harp and guitar arpeggios in a lantern-lit study',
    subtitle: 'Bundled CC0 WAV · public/music/instrumental/',
    genre: 'Acoustic Instrumental',
    category: 'instrumental',
    coverSceneId: 'japanese_study',
    src: './music/instrumental/lantern-acoustic-arp.wav',
    source: 'bundled_file',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 16,
  },
  {
    id: 'bundled_nocturne_felt_piano',
    title: 'Nocturne in Felt Piano',
    artist: 'Habitra Studio',
    description: 'Intimate felt piano chords and delicate upper-register melody',
    subtitle: 'Bundled CC0 WAV · public/music/instrumental/',
    genre: 'Felt Piano',
    category: 'instrumental',
    coverSceneId: 'night_library',
    src: './music/instrumental/nocturne-felt-piano.wav',
    source: 'bundled_file',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 16,
  },
  {
    id: 'lofi_rain',
    title: 'Lofi Rain (Live Synth)',
    artist: 'Habitra WebAudio Engine',
    description: 'Real-time generative Cmaj9 / Am9 / Fmaj7 / G13 lo-fi keys',
    subtitle: 'A calm rainy evening · procedural synth',
    genre: 'Lo-Fi Study Beats',
    category: 'rain',
    coverSceneId: 'study_room',
    source: 'procedural_synth',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 32,
  },
  {
    id: 'ambient_piano',
    title: 'Nocturne in Amber (Live Synth)',
    artist: 'Habitra WebAudio Engine',
    description: 'Generative Dm9 / Bbmaj9 soft felt piano progression',
    subtitle: 'Soft felt piano & warm tape · procedural synth',
    genre: 'Piano',
    category: 'instrumental',
    coverSceneId: 'night_library',
    source: 'procedural_synth',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 32,
  },
  {
    id: 'midnight_synth',
    title: 'Starlight Horizon (Live Synth)',
    artist: 'Habitra WebAudio Engine',
    description: 'Generative warm analog drift pads for night journeys',
    subtitle: 'Warm analog drift pads · procedural synth',
    genre: 'Ambient',
    category: 'ambient',
    coverSceneId: 'train_journey',
    source: 'procedural_synth',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 32,
  },
  {
    id: 'cozy_guitar',
    title: 'Espresso & Pages (Live Synth)',
    artist: 'Habitra WebAudio Engine',
    description: 'Generative mellow café acoustic chord voicings',
    subtitle: 'Mellow acoustic chords · procedural synth',
    genre: 'Café Acoustic',
    category: 'instrumental',
    coverSceneId: 'rainy_cafe',
    source: 'procedural_synth',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 32,
  },
  {
    id: 'cyber_chill',
    title: 'Emerald Canopy (Live Synth)',
    artist: 'Habitra WebAudio Engine',
    description: 'Generative binaural alpha focus wave',
    subtitle: 'Binaural alpha focus wave · procedural synth',
    genre: 'Deep Focus',
    category: 'focus',
    coverSceneId: 'forest_cabin',
    source: 'procedural_synth',
    license: 'CC0-1.0 Public Domain',
    durationSeconds: 32,
  },
  {
    id: 'silent',
    title: 'Silent Music Channel',
    artist: 'Habitra Studio',
    description: 'Mute music channel while keeping ambient soundscape active',
    subtitle: 'Ambient environment audio only',
    genre: 'Silent',
    category: 'ambient',
    coverSceneId: 'study_room',
    source: 'procedural_synth',
  },
];

export const DEFAULT_PLAYLISTS: UserPlaylist[] = [
  {
    id: 'playlist_deep_focus',
    name: 'Deep Focus & Coding',
    description: 'Steady harmonic progressions and lo-fi study chords for uninterrupted deep work',
    icon: '🎧',
    trackIds: [
      'bundled_midnight_study_chords',
      'bundled_deep_work_pulse',
      'cyber_chill',
      'bundled_nocturne_felt_piano',
    ],
    isBuiltIn: true,
  },
  {
    id: 'playlist_rainy_window',
    name: 'Rainy Window Café',
    description: 'Warm rainy lo-fi keys and acoustic café chords',
    icon: '🌧️',
    trackIds: [
      'bundled_velvet_rain_lofi',
      'lofi_rain',
      'cozy_guitar',
      'bundled_lantern_acoustic_arp',
    ],
    isBuiltIn: true,
  },
  {
    id: 'playlist_evening_unwind',
    name: 'Fireside & Nocturnes',
    description: 'Gentle felt piano, hearth drones, and starlight ambient pads',
    icon: '🔥',
    trackIds: [
      'bundled_cozy_hearth_drone',
      'bundled_nocturne_felt_piano',
      'ambient_piano',
      'bundled_starlight_drift_pad',
      'midnight_synth',
    ],
    isBuiltIn: true,
  },
  {
    id: 'playlist_woodland_retreat',
    name: 'Woodland Retreat',
    description: 'Harmonic forest breezes and acoustic arpeggios',
    icon: '🌲',
    trackIds: [
      'bundled_forest_breeze_harmonic',
      'bundled_lantern_acoustic_arp',
      'cyber_chill',
    ],
    isBuiltIn: true,
  },
];

export interface AmbientSoundMetadata {
  id: AmbientSoundId;
  name: string;
  description: string;
}

export const AMBIENT_SOUNDS: AmbientSoundMetadata[] = [
  { id: 'rain', name: 'Rain', description: 'Gentle rain on windowpane' },
  { id: 'forest', name: 'Forest', description: 'Woodland breeze & distant birds' },
  { id: 'ocean', name: 'Ocean', description: 'Rhythmic shoreline waves' },
  { id: 'cafe', name: 'Café', description: 'Cozy coffeehouse murmur' },
  { id: 'train', name: 'Train', description: 'Soothing rail cadence' },
  { id: 'fireplace', name: 'Fireplace', description: 'Warm hearth crackle' },
  { id: 'white_noise', name: 'White Noise', description: 'Crisp masking frequency' },
  { id: 'brown_noise', name: 'Brown Noise', description: 'Deep warm focus rumble' },
  { id: 'nature_night', name: 'Nature', description: 'Evening crickets & breeze' },
  { id: 'silent', name: 'Silent', description: 'No ambient soundscape' },
];

export const DEFAULT_PRESETS: SpacePreset[] = [
  {
    id: 'preset_living_sanctuary',
    name: 'Floating Sanctuary',
    subtitle: 'Lantern terrace, glowing river & fireflies',
    badgeIcon: '🏝️',
    sceneId: 'living_sanctuary',
    timeOfDay: 'night',
    weather: 'clear',
    lightingWarmth: 78,
    animationIntensity: 'high',
    musicTrackId: 'bundled_velvet_rain_lofi',
    ambientSoundId: 'nature_night',
    accentColor: '#14b8a6',
    uiTransparency: 76,
    focusMinutes: 45,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_spirit_blossom',
    name: 'Spirit Blossom',
    subtitle: 'Sakura island shrine & waterfall mist',
    badgeIcon: '🌸',
    sceneId: 'floating_garden',
    timeOfDay: 'evening',
    weather: 'clear',
    lightingWarmth: 82,
    animationIntensity: 'high',
    musicTrackId: 'bundled_emerald_moss_stream',
    ambientSoundId: 'forest',
    accentColor: '#ec4899',
    uiTransparency: 76,
    focusMinutes: 45,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_astral_archive',
    name: 'Astral Observatory',
    subtitle: 'Golden astrolabe, candles & starlight',
    badgeIcon: '🔭',
    sceneId: 'astral_observatory',
    timeOfDay: 'night',
    weather: 'clear',
    lightingWarmth: 85,
    animationIntensity: 'medium',
    musicTrackId: 'bundled_starlight_library_piano',
    ambientSoundId: 'fireplace',
    accentColor: '#f59e0b',
    uiTransparency: 78,
    focusMinutes: 50,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_rainy_study',
    name: 'Rainy Cabin',
    subtitle: 'Warm lamp, rain on glass, lo-fi chords',
    badgeIcon: '🌧',
    sceneId: 'study_room',
    timeOfDay: 'night',
    weather: 'rain',
    lightingWarmth: 78,
    animationIntensity: 'medium',
    musicTrackId: 'lofi_rain',
    ambientSoundId: 'rain',
    accentColor: '#6366f1',
    uiTransparency: 78,
    focusMinutes: 45,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_forest_focus',
    name: 'Forest',
    subtitle: 'Woodland mist, fireflies & acoustic calm',
    badgeIcon: '🌲',
    sceneId: 'forest_cabin',
    timeOfDay: 'evening',
    weather: 'clear',
    lightingWarmth: 65,
    animationIntensity: 'medium',
    musicTrackId: 'cyber_chill',
    ambientSoundId: 'forest',
    accentColor: '#10b981',
    uiTransparency: 80,
    focusMinutes: 45,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_cozy_cafe',
    name: 'Cozy Café',
    subtitle: 'Rainy streetlamps & espresso warmth',
    badgeIcon: '☕',
    sceneId: 'rainy_cafe',
    timeOfDay: 'evening',
    weather: 'rain',
    lightingWarmth: 85,
    animationIntensity: 'medium',
    musicTrackId: 'cozy_guitar',
    ambientSoundId: 'cafe',
    accentColor: '#f97316',
    uiTransparency: 80,
    focusMinutes: 30,
    shortBreakMinutes: 5,
  },
  {
    id: 'preset_train_journey',
    name: 'Train Journey',
    subtitle: 'Rhythmic rails across twilight peaks',
    badgeIcon: '🚆',
    sceneId: 'train_journey',
    timeOfDay: 'evening',
    weather: 'clear',
    lightingWarmth: 82,
    animationIntensity: 'medium',
    musicTrackId: 'midnight_synth',
    ambientSoundId: 'train',
    accentColor: '#f59e0b',
    uiTransparency: 76,
    focusMinutes: 50,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_library',
    name: 'Library',
    subtitle: 'Banker lamp, old books & hearth crackle',
    badgeIcon: '📚',
    sceneId: 'night_library',
    timeOfDay: 'night',
    weather: 'clear',
    lightingWarmth: 80,
    animationIntensity: 'low',
    musicTrackId: 'ambient_piano',
    ambientSoundId: 'fireplace',
    accentColor: '#22c55e',
    uiTransparency: 80,
    focusMinutes: 50,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_midnight_study',
    name: 'Midnight Room',
    subtitle: 'Deep night stillness & brown noise',
    badgeIcon: '🌙',
    sceneId: 'cozy_bedroom',
    timeOfDay: 'night',
    weather: 'heavy_rain',
    lightingWarmth: 60,
    animationIntensity: 'medium',
    musicTrackId: 'lofi_rain',
    ambientSoundId: 'brown_noise',
    accentColor: '#8b5cf6',
    uiTransparency: 82,
    focusMinutes: 60,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_night_city',
    name: 'Night City',
    subtitle: 'Neon skyline reflections & midnight rain',
    badgeIcon: '🌆',
    sceneId: 'night_city',
    timeOfDay: 'night',
    weather: 'storm',
    lightingWarmth: 45,
    animationIntensity: 'high',
    musicTrackId: 'lofi_rain',
    ambientSoundId: 'rain',
    accentColor: '#a855f7',
    uiTransparency: 75,
    focusMinutes: 50,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_cozy_home',
    name: 'Cozy Bedroom',
    subtitle: 'Tatami study & evening garden breeze',
    badgeIcon: '🏠',
    sceneId: 'japanese_study',
    timeOfDay: 'evening',
    weather: 'clear',
    lightingWarmth: 88,
    animationIntensity: 'low',
    musicTrackId: 'ambient_piano',
    ambientSoundId: 'nature_night',
    accentColor: '#eab308',
    uiTransparency: 78,
    focusMinutes: 40,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_ocean',
    name: 'Ocean',
    subtitle: 'Twilight ocean waves & horizon stars',
    badgeIcon: '🌊',
    sceneId: 'beach',
    timeOfDay: 'evening',
    weather: 'clear',
    lightingWarmth: 72,
    animationIntensity: 'medium',
    musicTrackId: 'midnight_synth',
    ambientSoundId: 'ocean',
    accentColor: '#38bdf8',
    uiTransparency: 76,
    focusMinutes: 45,
    shortBreakMinutes: 10,
  },
  {
    id: 'preset_fireplace_cabin',
    name: 'Fireplace Cabin',
    subtitle: 'Snowy alpine cabin & warm hearth fire',
    badgeIcon: '🔥',
    sceneId: 'mountain_cabin',
    timeOfDay: 'night',
    weather: 'snow',
    lightingWarmth: 90,
    animationIntensity: 'medium',
    musicTrackId: 'cozy_guitar',
    ambientSoundId: 'fireplace',
    accentColor: '#fb923c',
    uiTransparency: 80,
    focusMinutes: 50,
    shortBreakMinutes: 10,
  },
];

export interface RoomObjectCatalogItem {
  id: RoomObjectId;
  name: string;
  icon: string;
  description: string;
  unlockRequirementLabel: string;
  requiredStreak: number;
  requiredHabitsCompleted: number;
  requiredFocusHours: number;
  defaultX: number;
  defaultY: number;
}

export const ROOM_OBJECT_CATALOG: RoomObjectCatalogItem[] = [
  {
    id: 'panoramic_window',
    name: 'Panoramic Window',
    icon: '🪟',
    description: 'Rain-streaked pixel window overlooking the evening sky',
    unlockRequirementLabel: 'Starter Item (Always Unlocked)',
    requiredStreak: 0,
    requiredHabitsCompleted: 0,
    requiredFocusHours: 0,
    defaultX: 50,
    defaultY: 22,
  },
  {
    id: 'small_plant',
    name: 'Small Sprout Pot',
    icon: '🌱',
    description: 'A fresh green sprout that thrives on daily habits',
    unlockRequirementLabel: 'Starter Item (Always Unlocked)',
    requiredStreak: 0,
    requiredHabitsCompleted: 0,
    requiredFocusHours: 0,
    defaultX: 22,
    defaultY: 62,
  },
  {
    id: 'wall_clock',
    name: 'Pixel Wall Clock',
    icon: '🕰️',
    description: 'Synchronized ambient wall clock ticking softly',
    unlockRequirementLabel: 'Starter Item (Always Unlocked)',
    requiredStreak: 0,
    requiredHabitsCompleted: 0,
    requiredFocusHours: 0,
    defaultX: 78,
    defaultY: 20,
  },
  {
    id: 'desk_lamp',
    name: 'Warm Brass Lamp',
    icon: '🛋️',
    description: 'Casts a golden halo across your study desk',
    unlockRequirementLabel: 'Unlock: 3-Day Streak or 3 Habits Done',
    requiredStreak: 3,
    requiredHabitsCompleted: 3,
    requiredFocusHours: 0,
    defaultX: 34,
    defaultY: 56,
  },
  {
    id: 'stack_of_books',
    name: 'Study Grimoires',
    icon: '📚',
    description: 'Neatly stacked reference books and study journals',
    unlockRequirementLabel: 'Unlock: 5 Habits Completed or 1h Focus',
    requiredStreak: 0,
    requiredHabitsCompleted: 5,
    requiredFocusHours: 1,
    defaultX: 64,
    defaultY: 64,
  },
  {
    id: 'coffee_machine',
    name: 'Artisan Espresso Bar',
    icon: '☕',
    description: 'Steaming pour-over & espresso station for deep work',
    unlockRequirementLabel: 'Unlock: 7-Day Streak or 10 Habits Done',
    requiredStreak: 7,
    requiredHabitsCompleted: 10,
    requiredFocusHours: 2,
    defaultX: 82,
    defaultY: 58,
  },
  {
    id: 'potted_monstera',
    name: 'Lush Monstera Plant',
    icon: '🪴',
    description: 'Vibrant tropical foliage adding calm life to your corner',
    unlockRequirementLabel: 'Unlock: 10-Day Streak or 15 Habits Done',
    requiredStreak: 10,
    requiredHabitsCompleted: 15,
    requiredFocusHours: 3,
    defaultX: 15,
    defaultY: 70,
  },
  {
    id: 'bookshelf',
    name: 'Oak Library Shelf',
    icon: '🗄️',
    description: 'Tall wooden shelf filled with completed notebooks',
    unlockRequirementLabel: 'Unlock: 14-Day Streak or 25 Habits Done',
    requiredStreak: 14,
    requiredHabitsCompleted: 25,
    requiredFocusHours: 5,
    defaultX: 18,
    defaultY: 38,
  },
  {
    id: 'retro_computer',
    name: 'Mechanical Rig',
    icon: '🖥️',
    description: 'Custom dual-monitor pixel workstation with warm CRT glow',
    unlockRequirementLabel: 'Unlock: 18-Day Streak or 35 Habits Done',
    requiredStreak: 18,
    requiredHabitsCompleted: 35,
    requiredFocusHours: 8,
    defaultX: 48,
    defaultY: 55,
  },
  {
    id: 'upgraded_desk',
    name: 'Walnut Craft Desk',
    icon: '🪑',
    description: 'Spacious handcrafted walnut desk with cable organizer',
    unlockRequirementLabel: 'Unlock: 21-Day Streak or 45 Habits Done',
    requiredStreak: 21,
    requiredHabitsCompleted: 45,
    requiredFocusHours: 10,
    defaultX: 50,
    defaultY: 74,
  },
  {
    id: 'hanging_ivy',
    name: 'Cascading Wall Ivy',
    icon: '🌿',
    description: 'Trailing botanical vines framing the ceiling beams',
    unlockRequirementLabel: 'Unlock: 25-Day Streak or 60 Habits Done',
    requiredStreak: 25,
    requiredHabitsCompleted: 60,
    requiredFocusHours: 15,
    defaultX: 30,
    defaultY: 16,
  },
  {
    id: 'wall_posters',
    name: 'Framed Pixel Art',
    icon: '🖼️',
    description: 'Curated synthwave & lo-fi prints mounted on the wall',
    unlockRequirementLabel: 'Unlock: 30-Day Streak or 75 Habits Done',
    requiredStreak: 30,
    requiredHabitsCompleted: 75,
    requiredFocusHours: 20,
    defaultX: 66,
    defaultY: 26,
  },
  {
    id: 'hearth_fireplace',
    name: 'Crackling Hearth',
    icon: '🔥',
    description: 'Cozy stone fireplace radiating ember warmth',
    unlockRequirementLabel: 'Unlock: 45-Day Streak or 100 Habits Done',
    requiredStreak: 45,
    requiredHabitsCompleted: 100,
    requiredFocusHours: 30,
    defaultX: 85,
    defaultY: 74,
  },
  {
    id: 'sleeping_cat',
    name: 'Lo-Fi Ginger Cat',
    icon: '🐱',
    description: 'Purring pixel companion napping peacefully by your desk',
    unlockRequirementLabel: 'Unlock: 60-Day Master or 120 Habits Done',
    requiredStreak: 60,
    requiredHabitsCompleted: 120,
    requiredFocusHours: 40,
    defaultX: 40,
    defaultY: 78,
  },
];

export function createDefaultRoomLayout(): Record<RoomObjectId, RoomObjectPlacement> {
  const map = {} as Record<RoomObjectId, RoomObjectPlacement>;
  for (const item of ROOM_OBJECT_CATALOG) {
    map[item.id] = {
      id: item.id,
      x: item.defaultX,
      y: item.defaultY,
      visible: true,
    };
  }
  return map;
}

export function formatLocalYMD(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

export interface StarterHabitTemplate {
  id: string;
  name: string;
  icon: string;
  color: string;
  goalDays: number;
  reminderTime?: string;
  description: string;
}

export const STARTER_HABIT_TEMPLATES: StarterHabitTemplate[] = [
  {
    id: 'tpl_deep_focus',
    name: 'Deep Focus & Study Session',
    icon: '💻',
    color: '#14b8a6',
    goalDays: 30,
    reminderTime: '09:30',
    description: 'Dedicated distraction-free block for deep work or learning',
  },
  {
    id: 'tpl_reading',
    name: 'Read 20 Pages',
    icon: '📖',
    color: '#f59e0b',
    goalDays: 30,
    reminderTime: '21:00',
    description: 'Daily reading habit to wind down and expand perspective',
  },
  {
    id: 'tpl_hydration',
    name: 'Morning Hydration & Breath',
    icon: '💧',
    color: '#38bdf8',
    goalDays: 30,
    reminderTime: '08:00',
    description: 'Start the day with water and 5 minutes of mindful breathing',
  },
  {
    id: 'tpl_mobility',
    name: 'Mobility Stretch & Walk',
    icon: '🌿',
    color: '#10b981',
    goalDays: 21,
    reminderTime: '18:00',
    description: 'Step away from the desk to recharge posture and energy',
  },
  {
    id: 'tpl_journal',
    name: 'Evening Reflection Journal',
    icon: '📓',
    color: '#a855f7',
    goalDays: 30,
    reminderTime: '21:30',
    description: 'Capture three wins and reflections before sleep',
  },
];

export interface StarterReminderTemplate {
  id: string;
  title: string;
  type: 'water' | 'eye' | 'stretch' | 'study';
  scheduleType: 'interval' | 'daily';
  intervalMinutes?: number;
  timeOfDay?: string;
  icon: string;
  color: string;
}

export const STARTER_REMINDER_TEMPLATES: StarterReminderTemplate[] = [
  {
    id: 'tpl_rem_water',
    title: 'Hydration Check',
    type: 'water',
    scheduleType: 'interval',
    intervalMinutes: 60,
    icon: '💧',
    color: '#38bdf8',
  },
  {
    id: 'tpl_rem_eye',
    title: '20-20-20 Horizon Eye Break',
    type: 'eye',
    scheduleType: 'interval',
    intervalMinutes: 45,
    icon: '👁️',
    color: '#a855f7',
  },
  {
    id: 'tpl_rem_stretch',
    title: 'Posture & Stretch Reset',
    type: 'stretch',
    scheduleType: 'interval',
    intervalMinutes: 90,
    icon: '🧘',
    color: '#10b981',
  },
];

export function createDefaultAppState(): AppDataState {
  const now = new Date();
  const todayStr = formatLocalYMD(now);

  return {
    habits: [],
    completions: {},
    goals: [],
    reminders: [],
    environment: {
      sceneId: 'living_sanctuary',
      timeOfDay: 'night',
      weather: 'clear',
      lightingWarmth: 78,
      animationIntensity: 'high',
      particlesDensity: 75,
      uiTransparency: 76,
      uiPosition: 'standard',
      minimalMode: false,
      showProgressGardenObjects: true,
      showWorldHotspots: true,
      worldViewMode: 'living_world',
    },
    style: {
      pixelStyle: 'cozy',
      pixelDensity: 2,
      uiScale: 100,
      borderStyle: 'soft',
      panelStyle: 'glass',
      cornerRadius: 12,
      fontFamily: 'sans',
      accentColor: '#6366f1',
      bgOpacity: 85,
      panelOpacity: 80,
      animationSpeed: 'medium',
      glowEffects: true,
      screenEffects: false,
      highContrast: false,
      reducedMotion: false,
    },
    audio: {
      currentTrackId: 'bundled_velvet_rain_lofi',
      isPlaying: false,
      ambientPlaying: false,
      musicVolume: 40,
      ambientSoundId: 'rain',
      ambientVolume: 65,
      notificationVolume: 30,
      uiSoundVolume: 15,
      isMuted: false,
      customTracks: [],
      shuffle: false,
      repeatMode: 'all',
      autoSwitchMusicWithScene: false,
      favoriteTrackIds: [],
      activeCategory: 'all',
      playlists: DEFAULT_PLAYLISTS,
      activePlaylistId: null,
      recentlyPlayed: [],
      audioPresets: [
        {
          id: 'preset_audio_rainy_study',
          name: 'Rainy Study',
          musicTrackId: 'lofi_rain',
          musicVolume: 42,
          ambientSoundId: 'rain',
          ambientVolume: 68,
        },
        {
          id: 'preset_audio_deep_focus',
          name: 'Deep Focus',
          musicTrackId: 'ambient_piano',
          musicVolume: 35,
          ambientSoundId: 'brown_noise',
          ambientVolume: 50,
        },
        {
          id: 'preset_audio_night_coding',
          name: 'Night Coding',
          musicTrackId: 'midnight_synth',
          musicVolume: 45,
          ambientSoundId: 'nature_night',
          ambientVolume: 55,
        },
      ],
    },
    timer: {
      mode: 'focus',
      focusMinutes: 45,
      shortBreakMinutes: 10,
      longBreakMinutes: 20,
      customMinutes: 30,
      totalCycles: 4,
      currentCycle: 1,
      pomodoroAutoRepeat: false,
      immerseOnFocus: true,
      changeSceneOnBreak: false,
      muteNotificationsDuringFocus: false,
      sessionsCompletedToday: 0,
      totalFocusMinutesToday: 0,
      history: [],
      timerStatus: 'idle',
      startTimestamp: null,
      endTimestamp: null,
      pausedRemainingSeconds: null,
    },
    presets: DEFAULT_PRESETS,
    security: {
      passwordHash: null,
      salt: null,
      autoLockMinutes: 0,
      isLocked: false,
    },
    profile: {
      appName: 'Habitra',
      userName: '',
      userNameConfigured: false,
      quote: 'Small Habits. Big Life.',
      sidebarQuote: 'Discipline today creates the life you want tomorrow.',
      hasSeenWelcome: false,
      notificationsEnabled: true,
      notificationSoundEnabled: true,
      notifyHabits: true,
      notifyWater: true,
      notifyStudy: true,
      notifyBreaks: true,
      notifyTimer: true,
      notifyGoals: true,
      notifyStreak: true,
      quietHoursEnabled: false,
      quietHoursStart: '23:00',
      quietHoursEnd: '06:00',
      allowCriticalTimerInQuietHours: true,
      missedReminderBehavior: 'summary',
      keepRunningInBackground: true,
      startWithWindows: false,
      hasSeenTrayNotice: false,
      lowPowerBackgroundMode: true,
      xpEnabled: true,
      waterIntervalMinutes: 60,
      waterCompletedToday: 0,
      waterDailyGoal: 8,
      lastWaterDate: todayStr,
      lastWaterReminderAt: Date.now(),
      lastActiveTimestamp: Date.now(),
      currentActiveDateStr: todayStr,
      lastSavedAt: 'Just now',
      lastBackupAt: null,
    },
    notificationHistory: [],
    roomLayout: createDefaultRoomLayout(),
    journalEntries: {},
    versionedBackups: [],
  };
}
